config/routes.rb
Rails.application.routes.draw do

  root 'courses#index'

  resources :courses, :users

  # Authentication Routes
  get 'session/create'
  get 'session/logout'
  get 'session/updateprofile'
  put 'session/editprofile'
  post 'session/authenticate'
  # Course Routes
  post 'courses/search'
  post 'courses/createcategory'
  get 'courses/category/:id' => 'courses#category', as: 'course_category'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
class Ability
  include CanCan::Ability



  def initialize(user)

    alias_action :category, :search, to: :read
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

    user ||= User.new

    if user.admin?
        can :manage, :all
    else
        can :read, :all
        can :manage, User
    end

  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	has_many :course_category_mappers
	has_many :categories, through: :course_category_mappers
end

app/models/course_category.rb
class CourseCategory < ApplicationRecord
	has_many :course_category_mappers, foreign_key: 'category_id'
	has_many :courses, through: :course_category_mappers
end

app/models/course_category_mapper.rb
class CourseCategoryMapper < ApplicationRecord
	belongs_to :course
	belongs_to :course_category
end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include CanCan::ControllerAdditions
  include SessionHelper
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
	load_and_authorize_resource

	def index
		if is_login?
			@categories = CourseCategory.all
			@courses = Course.all
		else
			redirect_to :controller => 'session', :action => 'create'
		end
		
	end

	def category
		category = CourseCategory.find(params[:id])
		@courses = category.courses
		# render json: category
	end

	def new
		@course = Course.new
	end

	def create
		course = Course.new(course_params)
		course.save

		category = CourseCategory.find_by(:id => params[:category][:category])

		mapper = CourseCategoryMapper.create(course_id: course.id, category_id: category.id)
		mapper.save

		respond_to do |format|
			format.js
		end
	end

	def createcategory
		category = CourseCategory.create(name: params[:name], description: params[:description], active: params[:default_status])
		render json: category
	end

	def search
		
		@courses = Course.all

		if !params[:search][:title_search].blank?
			@courses = @courses.where('course_name LIKE ?', '%' + params[:search][:title_search] + '%')
		end

		if !params[:search][:search_course_date].blank?
			@courses = @courses.where('course_date = ?', params[:search][:search_course_date])
		end

		if !params[:search][:search_start_time].blank?
			@courses = @courses.where('course_start_time = ?', params[:search][:search_start_time])
		end

		respond_to do |format|
			format.js
			format.html
		end
		
	end

	private
		def course_params
			params.require(:course).permit(:course_id, :course_name, :course_description, :course_date, :course_start_time, :course_end_time)
		end
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def create
  	if is_login?
  		redirect_to :controller => 'site', :action => 'index'
  	else
	  	render :layout => false
	 end
  end

  def logout
    log_out
    redirect_to root_url
  end

  def authenticate
  	user = User.where('username = ? AND password = ?', params[:session][:email], Digest::SHA1.hexdigest(params[:session][:password])).first
  	if !user.nil?
  		login user.id
  		redirect_to :controller => 'courses', :action => 'index'
  	else
  		flash[:danger] = 'Login failed, please try again with valid information'
  		redirect_to :action => 'create'
  	end
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  	
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	load_and_authorize_resource
	
	def index
		
	end

	def edit
		@user = User.find(current_user.id)
	end

	def update
		@user = User.find(params[:id])
		respond_to do |format|
			if @user.update(user_params)
				format.js {render 'update'}
			else
				format.js {render 'update_error'}
			end
		end
	end

	private
		def user_params
			params.require(:user).permit(:firstname, :lastname, :nickname, :birthdate, :gender)
		end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/session_helper.rb
module SessionHelper
	def login(uid)
		session[:identity] = uid
	end
	def current_user
		@current_user ||= User.find_by_id(session[:identity])
	end
	def log_out
		session.delete(:identity)
		@current_user = nil
	end
	def is_login?
		!session[:identity].nil?
	end
	def the_ability
		@current_ability ||= Ability.new(current_user)
	end
	def is_admin?
		current_user.admin?
	end
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/courses/_remotesearch.html.erb
<div id="course-container">
	<% if !@courses.empty? %>
		<% @courses.each do |course| %>
			<div class="course-card">
				<!-- <div class="col-lg-12"> -->
				<p><%= course.course_id %></p>
				<h3><%= course.course_name %></h3>
				<p><%= course.course_description %></p>
				<p style="font-size:0.85em;">Date : <%= course.course_date.strftime('%A, %B %d, %Y') %></p>
				<p style="font-size:0.85em;">Time : <%= course.course_start_time.strftime('%I:%M %P') %> - <%= course.course_end_time.strftime('%I:%M %P') %></p>
				<div class="button-container">
					<%= link_to "View Details", 'details', :class => 'btn btn-primary btn-sm' %>
					<%= link_to "Book this class", 'book', :class => 'btn btn-success btn-sm' %>
				</div>
				<!-- </div> -->
			</div>
		<% end %>
	<% else %>
		<div class="alert alert-danger">No course found</div>
	<% end %>
</div>	

app/views/courses/category.js.erb
$('#course-container').hide().html('<%= j render('remotesearch') %>');
$('#course-container').fadeIn('slow');

app/views/courses/create.js.erb
$('#notification-area').html(
	'<div class="alert alert-success">Successfully created the course</div>'
);

app/views/courses/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			<div class="profile-box">
				<div class="profile-img-container">
					<div class="real-container">
						<i class="fa fa-user fa-3x"></i>
					</div>
				</div>
				<h4 class="text-center"><strong><%= current_user.firstname + ' ' + current_user.lastname %></strong></h4>
				<p class="text-center"><% if is_admin? %> Instructor <% else %> Student <% end %></p>
			</div>
			<h3 style="padding-bottom:10px; border-bottom:1px solid #515151;">Categories</h3>
			<ul class="nav nav-pills nav-stacked">
				<% @categories.each do |category| %>
					<li><%= link_to category.name, course_category_path(category.id), remote:true %></li>
				<% end %>
			</ul>
		</div>
		<div class="col-lg-9">
			<%= form_for :search, url: {action: 'search'}, remote:true do |f| %>
				<div class="row" style="margin:10px -15px;">
					<div class="col-lg-12">
						<%= f.text_field 'title_search', {class: 'form-control', placeholder: 'Course Search'} %>
					</div>
				</div>
				<div class="row" style="margin:10px -15px;">
					<div class="col-lg-4">
						<%= f.text_field 'search_course_date', {class: 'form-control', placeholder: 'Date e.g. 2017-01-01'} %>
					</div>
					<div class="col-lg-4">
						<%= f.text_field 'search_start_time', {class: 'form-control', placeholder: 'Start time e.g. 11:00:00'} %>
					</div>
					<div class="col-lg-4">
						<%= f.submit "Search Now", {class: 'btn btn-primary'} %>
					</div>
				</div>

			<% end %>
			<div id="course-container">
				<% @courses.each do |course| %>
					<div class="course-card">
						<!-- <div class="col-lg-12"> -->
						<p><%= course.course_id %></p>
						<h3><%= course.course_name %></h3>
						<p><%= course.course_description %></p>
						<p style="font-size:0.85em;">Date : <%= course.course_date.strftime('%A, %B %d, %Y') %></p>
						<p style="font-size:0.85em;">Time : <%= course.course_start_time.strftime('%I:%M %P') %> - <%= course.course_end_time.strftime('%I:%M %P') %></p>
						<div class="button-container">
							<%= link_to "View Details", '#', :class => 'btn btn-primary btn-sm' %>
							<%= link_to "Book this class", '#', :class => 'btn btn-success btn-sm' %>
						</div>
						<!-- </div> -->
					</div>
				<% end %>
			</div>	
		</div>
	</div>
</div>

app/views/courses/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-6" style="margin:0 auto; float:none;">
			<div class="alert alert-warning">
				<strong>Note:</strong> Only instructor & administrator can create a new course
			</div>
			<div id="notification-area">

			</div>
			<%= form_for @course, url: courses_path, remote: true do |f| %>
				<div class="form-group">
					<%= f.label :course_id %>
					<%= f.text_field :course_id, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :course_name %>
					<%= f.text_field :course_name, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :course_description %>
					<%= f.text_area :course_description, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :course_date %>
					<%= f.text_field :course_date, {class:'form-control', placeholder: 'yyyy-mm-dd (e.g. 2017-01-01)'} %>
				</div>
				<!-- <div class="form-group"> -->
				<div class="row">
					<div class="col-lg-8">
						<div class="form-group">
							<%= fields_for :category do |sub| %>
								<%=  sub.label 'category' %>
								<%= sub.collection_select 'category', CourseCategory.all, :id, :name, {}, {:class => 'form-control'}%>
							<% end %>
						</div>
					</div>
					<div class="col-lg-4" style="padding:25px 0;">
						<a href="#" id="adderer" class="btn btn-info">Add new category</a>
					</div>
					<!-- <div class="col-lg-4"></div> -->
				</div>
				<!-- </div> -->
				<div class="form-group">
					<%= f.label :course_start_time %>
					<%= f.text_field :course_start_time, {class:'form-control', placeholder: 'hh:mm:ss (e.g. 12:00:00)'} %>
				</div>
				<div class="form-group">
					<%= f.label :course_end_time %>
					<%= f.text_field :course_end_time, {class:'form-control', placeholder: 'hh:mm:ss (e.g. 12:00:00)'} %>
				</div>
				<div class="form-group">
					<%= f.label :max_students %>
					<%= f.text_field :max_students, {class:'form-control', placeholder: 'Number Only'} %>
				</div>
				<%= f.submit "Create new course", {class:'btn btn-primary btn-block'} %>
			<% end %>
		</div>
	</div>
</div>

<div class="modal fade" id="category-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
	<div class="modal-dialog modal-sm" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h3 class="modal-title">New Category</h3>
				<button type="button" class="close" data-dismiss="modal" aria-label="Close">
				  <span aria-hidden="true">&times;</span>
				</button>
			</div>
			<div class="modal-body">
				<form>
					<div class="form-group">
						<label for="category_name">Name</label>
						<input type="text" class="form-control" name="category_name" />
					</div>
					<div class="form-group">
						<label for="category_description">Description</label>
						<textarea class="form-control" name="category_description"></textarea>
					</div>
					<div class="form-group">
						<label for="category_name">Default Status</label>
						<select name="category_default_status" class="form-control">
							<option value="1">Active</option>
							<option value="0">Inactive</option>
						</select>
					</div>
					<div>
						<button type="button" id="create-new-category" class="btn btn-success">Create</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

app/views/courses/search.js.erb
$('#course-container').hide().html('<%= j render('remotesearch') %>');
$('#course-container').fadeIn('slow');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CourseManager</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="navbar navbar-inverse navbar-static-top" style="border-bottom:1px solid #dadada;">
  		<div class="container">
	  		<div class="navbar-header">
	  		 <%= link_to "COURSE MANAGER", root_url, {class: 'navbar-brand'} %>
	  		</div>
        <div class="navbar-collapse">
          <ul class="navbar-nav nav navbar-right">
            <li><%= link_to "Home", root_url %></li>
            <% if can? :manage, Course %>
              <li><%= link_to "Create New Course", {controller: 'courses', action:'new'} %></li>
            <% end %>
            <% if is_login? %>
              <li><%= link_to "Edit Profile", edit_user_path(:id => current_user.id) %></li>
              <li><%= link_to "Logout (" + current_user.username + ")", {controller: 'session', action:'logout'} %></li>
            <% end %>
          </ul>
        </div>
	  	</div>
  	</div>
    <%= yield %>
  </body>
</html>

app/views/session/create.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8" />
	<title>Login - Course Management Systems</title>
	<%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>
<body style="background-color:#337ab7;">
<div class="navbar navbar-light navbar-static-top">
	<div class="navbar-header">
		
	</div>
</div>
<div class="container">
	<div class="row" style="margin-top:50px;">
		<div class="col-lg-5" style="margin:0 auto; float:none;">
			<div class="well">
				<h3>Instruction</h3>
				<p style="font-size:0.8em;">1. Please visit github page to see the code via this
					<a href="https://github.com/chatthana/course_mgt">link</a>
					(p.s. Do not touch other projects. They are personal)
				</p>
				<p style="font-size:0.8em;">2. No datepicker, timepicker, or any fancy widgets for course search but I have already provided the format</p>
				<p style="font-size:0.8em;">3. All types of comments are welcomed</p>
			</div>
		</div>
	</div>
	<div class="row">
		<div class="col-lg-5 login-box">
			<h3>Signin</h3>
			<% flash.each do |k,v| %>
				<div class="alert alert-<%= k %>"><p><%= v %></p></div>
			<% end %>
				<%= form_for :session, url: {action: 'authenticate'} do |f| %>
					<div class="form-group">
						<%= f.text_field 'email', {class: 'form-control', placeholder: 'Email'} %>
					</div>
					<div class="form-group">
						<%= f.password_field 'password', {class: 'form-control', placeholder: 'Password'} %>
					</div>
					<%= f.submit 'Login', {class: 'btn btn-primary btn-block'} %>
				<% end %>
		</div>
	</div>
</div>
</body>
</html>

app/views/session/updateprofile.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-6" style="margin:0 auto; float:none;">
			<div class="alert alert-warning">
				<strong>Note:</strong> Only instructor & administrator can create a new course
			</div>
			<%= form_for @user, url: {action:'editprofile'}, method: :put, remote: true do |f| %>
				<div class="form-group">
					<%= f.label :firstname %>
					<%= f.text_field :firstname, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :lastname %>
					<%= f.text_field :lastname, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :nickname %>
					<%= f.text_field :nickname, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :birthdate %>
					<%= f.text_field :birthdate, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :gender %>
					<%= f.text_field :gender, {class:'form-control'} %>
				</div>
				<%= f.submit "Create new course", {class:'btn btn-primary btn-block'} %>
			<% end %>
		</div>
	</div>
</div>

app/views/site/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-3">
			
		</div>
		<div class="col-lg-9">
			<% @courses.each do |course| %>
				<div class="course-card card">
					<h3><%= course.course_name %></h3>
					<p><%= course.course_description %></p>
				</div>
			<% end %>
		</div>
	</div>
</div>

app/views/users/edit.html.erb
<div class="container">
	<div class="row">
		<div class="col-lg-6" style="margin:0 auto; float:none;">
			<div id="notification-area"></div>
			<%= form_for @user, remote: true do |f| %>
				<div class="form-group">
					<%= f.label :firstname %>
					<%= f.text_field :firstname, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :lastname %>
					<%= f.text_field :lastname, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :nickname %>
					<%= f.text_field :nickname, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :birthdate %>
					<%= f.text_field :birthdate, {class:'form-control'} %>
				</div>
				<div class="form-group">
					<%= f.label :gender %>
					<%= f.text_field :gender, {class:'form-control'} %>
				</div>
				<%= f.submit "Create new course", {class:'btn btn-primary btn-block'} %>
			<% end %>
		</div>
	</div>
</div>

app/views/users/update.js.erb
$('#notification-area').html(
	'<div class="alert alert-success">Successfully edit the profile</div>'
);

app/views/users/update_error.js.erb
$('#notification-area').html(
	'<div class="alert alert-danger">Unable to update the profile</div>'
);